name: dtest build and test

on: [ push, pull_request ]

jobs:
  test-ubuntu-20:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3

    - name: Build
      run: |
        make dtest dtest-cxx11 dtest-cxx14 dtest-cxx17 build-tests
        mkdir static
        make dtest-static STATIC_TARGET=static/dtest-static "STATIC_TESTS=$(find test/build/*/static/*.dtest.o -printf '%p ')" EXTRACXXFLAGS=-fopenmp

    - name: Run tests (default)
      if: ${{ always() }}
      run: ./dtest test/build

    - name: Dump results (default)
      if: ${{ always() }}
      run: cat dtest.log.json

    - name: Run tests (default-static)
      if: ${{ always() }}
      run: cd static && ./dtest-static

    - name: Dump results (default-static)
      if: ${{ always() }}
      run: cat static/dtest.log.json

    - name: Run tests (c++11)
      if: ${{ always() }}
      run: ./dtest-cxx11 test/build

    - name: Dump results (c++11)
      if: ${{ always() }}
      run: cat dtest.log.json

    - name: Run tests (c++14)
      if: ${{ always() }}
      run: ./dtest-cxx14 test/build

    - name: Dump results (c++14)
      if: ${{ always() }}
      run: cat dtest.log.json

    - name: Run tests (c++17)
      if: ${{ always() }}
      run: ./dtest-cxx17 test/build

    - name: Dump results (c++17)
      if: ${{ always() }}
      run: cat dtest.log.json

  test-ubuntu-22:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3

    - name: Build
      run: |
        make dtest dtest-cxx11 dtest-cxx14 dtest-cxx17 build-tests
        mkdir static
        make dtest-static STATIC_TARGET=static/dtest-static "STATIC_TESTS=$(find test/build/*/static/*.dtest.o -printf '%p ')" EXTRACXXFLAGS=-fopenmp

    - name: Run tests (default)
      if: ${{ always() }}
      run: ./dtest test/build

    - name: Dump results (default)
      if: ${{ always() }}
      run: cat dtest.log.json

    - name: Run tests (default-static)
      if: ${{ always() }}
      run: cd static && ./dtest-static

    - name: Dump results (default-static)
      if: ${{ always() }}
      run: cat static/dtest.log.json

    - name: Run tests (c++11)
      if: ${{ always() }}
      run: ./dtest-cxx11 test/build

    - name: Dump results (c++11)
      if: ${{ always() }}
      run: cat dtest.log.json

    - name: Run tests (c++14)
      if: ${{ always() }}
      run: ./dtest-cxx14 test/build

    - name: Dump results (c++14)
      if: ${{ always() }}
      run: cat dtest.log.json

    - name: Run tests (c++17)
      if: ${{ always() }}
      run: ./dtest-cxx17 test/build

    - name: Dump results (c++17)
      if: ${{ always() }}
      run: cat dtest.log.json
